"""
Manages Twitch Miner subprocess lifecycles.

Each miner instance runs as a separate Python subprocess with its own:
  - run.py (generated config)
  - cookies/ folder (persisted across restarts)
  - logs/ folder (tailed for WebSocket streaming)
"""

import asyncio
import logging
import os
import signal
import sys
from datetime import datetime, timezone
from pathlib import Path

from sqlalchemy import select, update
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings
from app.models.database import MinerInstance, async_session
from app.models.enums import InstanceState

logger = logging.getLogger(__name__)



class MinerProcessManager:
    """Singleton that tracks all running miner subprocesses."""

    async def cleanup_orphan_processes(self):
        """Clean local process/watch task caches and reconcile DB process states."""
        to_remove = []
        for instance_id, proc in self._processes.items():
            if proc.returncode is not None:
                to_remove.append(instance_id)
            else:
                try:
                    os.kill(proc.pid, 0)
                except OSError:
                    to_remove.append(instance_id)
        for instance_id in to_remove:
            logger.info(f"Removing orphaned tracked process: {instance_id}")
            self._processes.pop(instance_id, None)
            self._watch_tasks.pop(instance_id, None)

        await self.reconcile_all_on_startup()

    def __init__(self):
        self._processes: dict[str, asyncio.subprocess.Process] = {}
        self._watch_tasks: dict[str, asyncio.Task] = {}
        self._analytics_ports: dict[str, int] = {}  # instance_id -> port mapping
        self._next_analytics_port = 5000

    @staticmethod
    def _pid_exists(pid: int | None) -> bool:
        if pid is None or pid <= 0:
            return False
        try:
            os.kill(pid, 0)
        except ProcessLookupError:
            return False
        except PermissionError:
            return True
        except OSError:
            return False
        return True

    @staticmethod
    def _signal_process(pid: int, sig: signal.Signals) -> None:
        if os.name == "nt":
            os.kill(pid, sig)
            return
        os.killpg(os.getpgid(pid), sig)

    async def _wait_for_pid_exit(self, pid: int, timeout_seconds: int) -> bool:
        deadline = asyncio.get_event_loop().time() + timeout_seconds
        while asyncio.get_event_loop().time() < deadline:
            if not self._pid_exists(pid):
                return True
            await asyncio.sleep(0.2)
        return not self._pid_exists(pid)

    def _allocate_analytics_port(self, instance_id: str) -> int:
        """Allocate a unique port for analytics."""
        if instance_id in self._analytics_ports:
            return self._analytics_ports[instance_id]
        
        port = self._next_analytics_port
        self._analytics_ports[instance_id] = port
        self._next_analytics_port += 1
        return port

    def _release_analytics_port(self, instance_id: str) -> None:
        """Release the analytics port."""
        self._analytics_ports.pop(instance_id, None)

    def _generate_run_script(
        self,
        instance_dir: Path,
        twitch_username: str,
        streamers: list[str],
        enable_analytics: bool = False,
        analytics_port: int | None = None,
    ) -> Path:
        """Create a run.py based on the official example.py with sensible defaults."""
        streamer_lines = "\n".join(f'        "{s}",' for s in streamers)

        miner_repo_path = settings.MINER_REPO_PATH
        sys_path_insert = ""
        if miner_repo_path:
            expanded_path = str(Path(miner_repo_path).expanduser())
            sys_path_insert = (
                f'import sys\n'
                f'sys.path.insert(0, "{expanded_path}")\n\n'
            )

        analytics_call = ""
        if enable_analytics and analytics_port:
            analytics_call = f'twitch_miner.analytics(host="0.0.0.0", port={analytics_port}, refresh=5, days_ago=7)\n'

        script = (
            "# -*- coding: utf-8 -*-\n"
            "# Auto-generated by Twitch Miner Backend\n"
            "\n"
            f"{sys_path_insert}"
            "import logging\n"
            "from colorama import Fore\n"
            "from TwitchChannelPointsMiner import TwitchChannelPointsMiner\n"
            "from TwitchChannelPointsMiner.logger import LoggerSettings, ColorPalette\n"
            "from TwitchChannelPointsMiner.classes.Chat import ChatPresence\n"
            "from TwitchChannelPointsMiner.classes.Settings import Priority, Events, FollowersOrder\n"
            "from TwitchChannelPointsMiner.classes.entities.Bet import Strategy, BetSettings, Condition, OutcomeKeys, FilterCondition, DelayMode\n"
            "from TwitchChannelPointsMiner.classes.entities.Streamer import Streamer, StreamerSettings\n"
            "\n"
            "twitch_miner = TwitchChannelPointsMiner(\n"
            f'    username="{twitch_username}",\n'
            "    claim_drops_startup=True,\n"
            "    priority=[\n"
            "        Priority.STREAK,\n"
            "        Priority.DROPS,\n"
            "        Priority.ORDER,\n"
            "    ],\n"
            f"    enable_analytics={str(enable_analytics)},\n"
            "    disable_ssl_cert_verification=False,\n"
            "    logger_settings=LoggerSettings(\n"
            "        save=True,\n"
            "        console_level=logging.INFO,\n"
            "        console_username=False,\n"
            "        auto_clear=True,\n"
            "        file_level=logging.INFO,\n"
            "        emoji=True,\n"
            "        less=False,\n"
            "        colored=False,\n"
            "        color_palette=ColorPalette(\n"
            '            STREAMER_online="GREEN",\n'
            '            streamer_offline="red",\n'
            "            BET_wiN=Fore.MAGENTA,\n"
            "        ),\n"
            "    ),\n"
            "    streamer_settings=StreamerSettings(\n"
            "        make_predictions=True,\n"
            "        follow_raid=True,\n"
            "        claim_drops=True,\n"
            "        claim_moments=True,\n"
            "        watch_streak=True,\n"
            "        community_goals=False,\n"
            "        chat=ChatPresence.ONLINE,\n"
            "        bet=BetSettings(\n"
            "            strategy=Strategy.SMART,\n"
            "            percentage=5,\n"
            "            percentage_gap=20,\n"
            "            max_points=50000,\n"
            "            stealth_mode=True,\n"
            "            delay_mode=DelayMode.FROM_END,\n"
            "            delay=6,\n"
            "            minimum_points=20000,\n"
            "            filter_condition=FilterCondition(\n"
            "                by=OutcomeKeys.TOTAL_USERS,\n"
            "                where=Condition.LTE,\n"
            "                value=800,\n"
            "            ),\n"
            "        ),\n"
            "    ),\n"
            ")\n"
            "\n"
            f"{analytics_call}"
            "twitch_miner.mine(\n"
            "    [\n"
            f"{streamer_lines}\n"
            "    ],\n"
            "    followers=False,\n"
            "    followers_order=FollowersOrder.ASC,\n"
            ")\n"
        )

        run_path = instance_dir / "run.py"
        run_path.write_text(script)
        return run_path

    def _ensure_instance_dir(self, instance_id: str) -> Path:
        """Create and return the instance's data directory."""
        instance_dir = settings.INSTANCES_DIR / instance_id
        (instance_dir / "cookies").mkdir(parents=True, exist_ok=True)
        (instance_dir / "logs").mkdir(parents=True, exist_ok=True)
        (instance_dir / "analytics").mkdir(parents=True, exist_ok=True)
        return instance_dir

    async def _update_instance_status(
        self,
        instance_id: str,
        *,
        status: InstanceState,
        pid: int | None = None,
        analytics_port: int | None = None,
        set_last_started_at: bool = False,
        set_last_stopped_at: bool = False,
        db_session: AsyncSession | None = None,
    ) -> None:
        if db_session is not None:
            result = await db_session.execute(
                select(MinerInstance).where(MinerInstance.id == instance_id)
            )
            inst = result.scalar_one_or_none()
            if not inst:
                return

            inst.status = status
            inst.pid = pid
            if analytics_port is not None:
                inst.analytics_port = analytics_port
            if set_last_started_at:
                inst.last_started_at = datetime.now(timezone.utc)
            if set_last_stopped_at:
                inst.last_stopped_at = datetime.now(timezone.utc)
            await db_session.commit()
            return

        async with async_session() as db:
            result = await db.execute(
                select(MinerInstance).where(MinerInstance.id == instance_id)
            )
            inst = result.scalar_one_or_none()
            if not inst:
                return

            inst.status = status
            inst.pid = pid
            if analytics_port is not None:
                inst.analytics_port = analytics_port
            if set_last_started_at:
                inst.last_started_at = datetime.now(timezone.utc)
            if set_last_stopped_at:
                inst.last_stopped_at = datetime.now(timezone.utc)
            await db.commit()

    async def _reserve_instance_start(self, instance_id: str, db_session: AsyncSession | None = None) -> bool:
        """Atomically reserve instance startup to prevent concurrent starts across workers."""
        if db_session is not None:
            result = await db_session.execute(
                update(MinerInstance)
                .where(
                    MinerInstance.id == instance_id,
                    MinerInstance.status == InstanceState.STOPPED,
                )
                .values(
                    status=InstanceState.RUNNING,
                    pid=0,
                    last_started_at=datetime.now(timezone.utc),
                )
            )
            await db_session.commit()
            return (result.rowcount or 0) == 1

        async with async_session() as db:
            result = await db.execute(
                update(MinerInstance)
                .where(
                    MinerInstance.id == instance_id,
                    MinerInstance.status == InstanceState.STOPPED,
                )
                .values(
                    status=InstanceState.RUNNING,
                    pid=0,
                    last_started_at=datetime.now(timezone.utc),
                )
            )
            await db.commit()
            return (result.rowcount or 0) == 1

    async def reconcile_instance_status(self, instance_id: str, db_session: AsyncSession | None = None) -> None:
        """Synchronize a DB instance state with real process existence."""
        if db_session is not None:
            result = await db_session.execute(
                select(MinerInstance).where(MinerInstance.id == instance_id)
            )
            inst = result.scalar_one_or_none()
            if not inst:
                return

            if inst.status != InstanceState.RUNNING:
                return

            if not self._pid_exists(inst.pid):
                inst.status = InstanceState.STOPPED
                inst.pid = None
                inst.last_stopped_at = datetime.now(timezone.utc)
                await db_session.commit()
            return

        async with async_session() as db:
            result = await db.execute(
                select(MinerInstance).where(MinerInstance.id == instance_id)
            )
            inst = result.scalar_one_or_none()
            if not inst:
                return

            if inst.status != InstanceState.RUNNING:
                return

            if not self._pid_exists(inst.pid):
                inst.status = InstanceState.STOPPED
                inst.pid = None
                inst.last_stopped_at = datetime.now(timezone.utc)
                await db.commit()

    async def reconcile_all_on_startup(self):
        """Mark stale non-stopped instances as STOPPED if their OS process is gone."""
        async with async_session() as db:
            result = await db.execute(
                select(MinerInstance).where(MinerInstance.status != InstanceState.STOPPED)
            )
            instances = result.scalars().all()

            changed = 0
            for inst in instances:
                if not self._pid_exists(inst.pid):
                    inst.status = InstanceState.STOPPED
                    inst.pid = None
                    inst.last_stopped_at = datetime.now(timezone.utc)
                    changed += 1

            if changed > 0:
                await db.commit()
                logger.info(f"Reconciled {changed} stale instance(s) to STOPPED")

    async def start(
        self,
        instance_id: str,
        twitch_username: str,
        streamers: list[str],
        enable_analytics: bool = False,
        db_session: AsyncSession | None = None,
    ) -> int:
        """
        Start the miner subprocess. Returns the OS PID.
        Raises RuntimeError if already running.
        """
        # Allocate analytics port if needed
        analytics_port = None
        if enable_analytics:
            analytics_port = self._allocate_analytics_port(instance_id)

        reserved = await self._reserve_instance_start(instance_id, db_session=db_session)
        if not reserved:
            self._release_analytics_port(instance_id)
            raise RuntimeError(f"Instance {instance_id} is already running or transitioning")

        # Analytics run on allocated port
        analytics_port = analytics_port if enable_analytics else None

        instance_dir = self._ensure_instance_dir(instance_id)
        run_script = self._generate_run_script(
            instance_dir, twitch_username, streamers, enable_analytics, analytics_port
        )

        env = {**os.environ, "PYTHONUNBUFFERED": "1", "PYTHONIOENCODING": "utf-8"}
        kwargs = {"start_new_session": True}

        try:
            process = await asyncio.create_subprocess_exec(
                sys.executable, str(run_script),
                cwd=str(instance_dir),
                stdout=asyncio.subprocess.DEVNULL,
                stderr=asyncio.subprocess.DEVNULL,
                env=env,
                **kwargs,
            )
        except Exception:
            self._release_analytics_port(instance_id)
            await self._update_instance_status(
                instance_id,
                status=InstanceState.STOPPED,
                pid=None,
                db_session=db_session,
            )
            raise

        self._processes[instance_id] = process
        logger.info(f"Started miner instance {instance_id} with PID {process.pid}")

        task = asyncio.create_task(self._watch_process(instance_id, process))
        self._watch_tasks[instance_id] = task

        await self._update_instance_status(
            instance_id,
            status=InstanceState.RUNNING,
            pid=process.pid,
            analytics_port=analytics_port,
            db_session=db_session,
        )

        return process.pid

    async def _watch_process(
        self,
        instance_id: str,
        process: asyncio.subprocess.Process,
    ):
        """Wait for process exit and synchronize in-memory/DB state."""
        try:
            await process.wait()
            logger.info(f"Miner instance {instance_id} exited with code {process.returncode}")
            self._processes.pop(instance_id, None)
            self._watch_tasks.pop(instance_id, None)
            self._release_analytics_port(instance_id)

            await self._update_instance_status(
                instance_id,
                status=InstanceState.STOPPED,
                pid=None,
                analytics_port=None,
                set_last_stopped_at=True,
            )
        except Exception as e:
            logger.error(f"Error watching process for {instance_id}: {e}")

    async def stop(self, instance_id: str, db_session: AsyncSession | None = None) -> bool:
        """
        Gracefully stop a miner and wait until the process has fully exited.

        1. Sets DB status to STOPPING immediately (so other requests see it).
        2. Sends SIGTERM to let the miner close WebSocket / IRC cleanly.
        3. Falls back to force-kill after *GRACEFUL_TIMEOUT* seconds.
        4. Sets DB status to STOPPED before returning.

        The caller (stop endpoint) blocks until this method returns,
        so the frontend receives the response only when shutdown is complete.

        Returns True if stopped, False if wasn't running.
        """
        GRACEFUL_TIMEOUT = 30  # seconds to wait for graceful shutdown
        FORCE_TIMEOUT = 10    # seconds to wait after force-kill

        if db_session is not None:
            result = await db_session.execute(
                select(MinerInstance).where(MinerInstance.id == instance_id)
            )
            inst = result.scalar_one_or_none()
            if not inst or inst.status == InstanceState.STOPPED or not self._pid_exists(inst.pid):
                if inst and inst.status != InstanceState.STOPPED:
                    inst.status = InstanceState.STOPPED
                    inst.pid = None
                    inst.last_stopped_at = datetime.now(timezone.utc)
                    await db_session.commit()
                return False
            pid = inst.pid
        else:
            async with async_session() as db:
                result = await db.execute(
                    select(MinerInstance).where(MinerInstance.id == instance_id)
                )
                inst = result.scalar_one_or_none()
                if not inst or inst.status == InstanceState.STOPPED or not self._pid_exists(inst.pid):
                    if inst and inst.status != InstanceState.STOPPED:
                        inst.status = InstanceState.STOPPED
                        inst.pid = None
                        inst.last_stopped_at = datetime.now(timezone.utc)
                        await db.commit()
                    return False
                pid = inst.pid

        logger.info(f"Stopping miner instance {instance_id} (PID {pid})")

        await self._update_instance_status(
            instance_id,
            status=InstanceState.STOPPING,
            pid=pid,
            db_session=db_session,
        )

        try:
            self._signal_process(pid, signal.SIGTERM)
        except (ProcessLookupError, PermissionError, OSError) as e:
            logger.debug(f"Graceful signal for PID {pid}: {e}")

        local_proc = self._processes.get(instance_id)
        try:
            if local_proc and local_proc.returncode is None:
                await asyncio.wait_for(local_proc.wait(), timeout=GRACEFUL_TIMEOUT)
            else:
                exited = await self._wait_for_pid_exit(pid, GRACEFUL_TIMEOUT)
                if not exited:
                    raise asyncio.TimeoutError
            logger.info(
                f"Instance {instance_id} (PID {pid}) exited gracefully"
            )
        except asyncio.TimeoutError:
            logger.warning(
                f"Graceful stop timed out after {GRACEFUL_TIMEOUT}s for "
                f"instance {instance_id} (PID {pid}), force-killing"
            )
            try:
                self._signal_process(pid, signal.SIGKILL)
            except (ProcessLookupError, PermissionError, OSError):
                pass

            try:
                if local_proc and local_proc.returncode is None:
                    await asyncio.wait_for(local_proc.wait(), timeout=FORCE_TIMEOUT)
                else:
                    await self._wait_for_pid_exit(pid, FORCE_TIMEOUT)
            except (asyncio.TimeoutError, ProcessLookupError):
                pass

        watch_task = self._watch_tasks.get(instance_id)
        if watch_task and not watch_task.done():
            try:
                await asyncio.wait_for(watch_task, timeout=5)
            except (asyncio.TimeoutError, asyncio.CancelledError):
                watch_task.cancel()

        self._processes.pop(instance_id, None)
        self._watch_tasks.pop(instance_id, None)
        self._release_analytics_port(instance_id)

        await self._update_instance_status(
            instance_id,
            status=InstanceState.STOPPED,
            pid=None,
            analytics_port=None,
            set_last_stopped_at=True,
            db_session=db_session,
        )

        return True

    def is_process_tracked(self, instance_id: str) -> bool:
        """Backward-compatible helper used by tests and same-worker guards."""
        proc = self._processes.get(instance_id)
        return proc is not None and proc.returncode is None

    async def shutdown_all(self):
        """Stop all running miners (called on app shutdown)."""
        for instance_id in list(self._processes.keys()):
            await self.stop(instance_id)


# Global singleton
miner_manager = MinerProcessManager()
