"""
Manages Twitch Miner subprocess lifecycles.

Each instance runs as a separate Python subprocess with its own:
  - run.py (generated config)
  - cookies/ folder (persisted across restarts)
  - logs/ folder (tailed for SSE streaming)
"""

import asyncio
import logging
import os
import signal
import sys
from datetime import datetime, timezone
from pathlib import Path

from sqlalchemy import select, update
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings
from app.models.database import MinerInstance, async_session
from app.models.enums import InstanceState

logger = logging.getLogger(__name__)


class MinerProcessManager:
    """Singleton that tracks all running miner subprocesses."""

    def __init__(self):
        self._processes: dict[str, asyncio.subprocess.Process] = {}
        self._watch_tasks: dict[str, asyncio.Task] = {}
        self._analytics_ports: dict[str, int] = {}
        self._next_analytics_port = 6000

    # ------------------------------------------------------------------
    # PID / signal helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _pid_exists(pid: int | None) -> bool:
        if pid is None or pid <= 0:
            return False
        try:
            os.kill(pid, 0)
        except ProcessLookupError:
            return False
        except PermissionError:
            return True
        except OSError:
            return False
        return True

    @staticmethod
    def _signal_process(pid: int, sig: signal.Signals) -> None:
        if os.name == "nt":
            os.kill(pid, sig)
        else:
            os.killpg(os.getpgid(pid), sig)

    async def _wait_for_pid_exit(self, pid: int, timeout_seconds: int) -> bool:
        deadline = asyncio.get_event_loop().time() + timeout_seconds
        while asyncio.get_event_loop().time() < deadline:
            if not self._pid_exists(pid):
                return True
            await asyncio.sleep(0.2)
        return not self._pid_exists(pid)

    # ------------------------------------------------------------------
    # Analytics port allocation
    # ------------------------------------------------------------------

    def _allocate_analytics_port(self, instance_id: str) -> int:
        if instance_id in self._analytics_ports:
            return self._analytics_ports[instance_id]
        port = self._next_analytics_port
        self._analytics_ports[instance_id] = port
        self._next_analytics_port += 1
        return port

    def _release_analytics_port(self, instance_id: str) -> None:
        self._analytics_ports.pop(instance_id, None)

    # ------------------------------------------------------------------
    # Run script generation
    # ------------------------------------------------------------------

    def _generate_run_script(
        self,
        instance_dir: Path,
        twitch_username: str,
        streamers: list[str],
        enable_analytics: bool = False,
        analytics_port: int | None = None,
    ) -> Path:
        streamer_lines = "\n".join(f'        "{s}",' for s in streamers)

        sys_path_insert = ""
        if settings.MINER_REPO_PATH:
            expanded = str(Path(settings.MINER_REPO_PATH).expanduser())
            sys_path_insert = f'import sys\nsys.path.insert(0, "{expanded}")\n\n'

        analytics_call = ""
        if enable_analytics and analytics_port:
            analytics_call = (
                f'twitch_miner.analytics(host="0.0.0.0", port={analytics_port}, refresh=5, days_ago=7)\n'
            )

        script = (
            "# -*- coding: utf-8 -*-\n"
            "# Auto-generated by Twitch Miner Backend\n"
            "\n"
            f"{sys_path_insert}"
            "import logging\n"
            "from colorama import Fore\n"
            "from TwitchChannelPointsMiner import TwitchChannelPointsMiner\n"
            "from TwitchChannelPointsMiner.logger import LoggerSettings, ColorPalette\n"
            "from TwitchChannelPointsMiner.classes.Chat import ChatPresence\n"
            "from TwitchChannelPointsMiner.classes.Settings import Priority, Events, FollowersOrder\n"
            "from TwitchChannelPointsMiner.classes.entities.Bet import Strategy, BetSettings, Condition, OutcomeKeys, FilterCondition, DelayMode\n"
            "from TwitchChannelPointsMiner.classes.entities.Streamer import Streamer, StreamerSettings\n"
            "\n"
            "twitch_miner = TwitchChannelPointsMiner(\n"
            f'    username="{twitch_username}",\n'
            "    claim_drops_startup=True,\n"
            "    priority=[\n"
            "        Priority.STREAK,\n"
            "        Priority.DROPS,\n"
            "        Priority.ORDER,\n"
            "    ],\n"
            f"    enable_analytics={str(enable_analytics)},\n"
            "    disable_ssl_cert_verification=False,\n"
            "    logger_settings=LoggerSettings(\n"
            "        save=True,\n"
            "        console_level=logging.INFO,\n"
            "        console_username=False,\n"
            "        auto_clear=True,\n"
            "        file_level=logging.INFO,\n"
            "        emoji=True,\n"
            "        less=False,\n"
            "        colored=False,\n"
            "        color_palette=ColorPalette(\n"
            '            STREAMER_online="GREEN",\n'
            '            streamer_offline="red",\n'
            "            BET_wiN=Fore.MAGENTA,\n"
            "        ),\n"
            "    ),\n"
            "    streamer_settings=StreamerSettings(\n"
            "        make_predictions=True,\n"
            "        follow_raid=True,\n"
            "        claim_drops=True,\n"
            "        claim_moments=True,\n"
            "        watch_streak=True,\n"
            "        community_goals=False,\n"
            "        chat=ChatPresence.ONLINE,\n"
            "        bet=BetSettings(\n"
            "            strategy=Strategy.SMART,\n"
            "            percentage=5,\n"
            "            percentage_gap=20,\n"
            "            max_points=50000,\n"
            "            stealth_mode=True,\n"
            "            delay_mode=DelayMode.FROM_END,\n"
            "            delay=6,\n"
            "            minimum_points=20000,\n"
            "            filter_condition=FilterCondition(\n"
            "                by=OutcomeKeys.TOTAL_USERS,\n"
            "                where=Condition.LTE,\n"
            "                value=800,\n"
            "            ),\n"
            "        ),\n"
            "    ),\n"
            ")\n"
            "\n"
            f"{analytics_call}"
            "twitch_miner.mine(\n"
            "    [\n"
            f"{streamer_lines}\n"
            "    ],\n"
            "    followers=False,\n"
            "    followers_order=FollowersOrder.ASC,\n"
            ")\n"
        )

        run_path = instance_dir / "run.py"
        run_path.write_text(script, encoding="utf-8")
        return run_path

    def _ensure_instance_dir(self, instance_id: str) -> Path:
        instance_dir = settings.INSTANCES_DIR / instance_id
        (instance_dir / "cookies").mkdir(parents=True, exist_ok=True)
        (instance_dir / "logs").mkdir(parents=True, exist_ok=True)
        return instance_dir

    # ------------------------------------------------------------------
    # DB helpers
    # ------------------------------------------------------------------

    async def _update_instance_status(
        self,
        instance_id: str,
        *,
        status: InstanceState,
        pid: int | None = None,
        analytics_port: int | None = None,
        set_last_started_at: bool = False,
        set_last_stopped_at: bool = False,
        db_session: AsyncSession | None = None,
    ) -> None:
        async def _do(db: AsyncSession) -> None:
            result = await db.execute(
                select(MinerInstance).where(MinerInstance.id == instance_id)
            )
            inst = result.scalar_one_or_none()
            if not inst:
                return
            inst.status = status
            inst.pid = pid
            if analytics_port is not None:
                inst.analytics_port = analytics_port
            if set_last_started_at:
                inst.last_started_at = datetime.now(timezone.utc)
            if set_last_stopped_at:
                inst.last_stopped_at = datetime.now(timezone.utc)
            await db.commit()

        if db_session is not None:
            await _do(db_session)
        else:
            async with async_session() as db:
                await _do(db)

    async def _reserve_instance_start(
        self, instance_id: str, db_session: AsyncSession | None = None
    ) -> bool:
        stmt = (
            update(MinerInstance)
            .where(
                MinerInstance.id == instance_id,
                MinerInstance.status == InstanceState.STOPPED,
            )
            .values(
                status=InstanceState.RUNNING,
                pid=0,
                last_started_at=datetime.now(timezone.utc),
            )
        )
        if db_session is not None:
            result = await db_session.execute(stmt)
            await db_session.commit()
            return (result.rowcount or 0) == 1
        async with async_session() as db:
            result = await db.execute(stmt)
            await db.commit()
            return (result.rowcount or 0) == 1

    # ------------------------------------------------------------------
    # Process lifecycle
    # ------------------------------------------------------------------

    async def start(
        self,
        instance_id: str,
        twitch_username: str,
        streamers: list[str],
        enable_analytics: bool = False,
        db_session: AsyncSession | None = None,
    ) -> int:
        """Start the miner subprocess. Returns the OS PID."""
        analytics_port = self._allocate_analytics_port(instance_id) if enable_analytics else None

        reserved = await self._reserve_instance_start(instance_id, db_session=db_session)
        if not reserved:
            self._release_analytics_port(instance_id)
            raise RuntimeError(f"Instance {instance_id} is already running or transitioning")

        instance_dir = self._ensure_instance_dir(instance_id)
        run_script = self._generate_run_script(
            instance_dir, twitch_username, streamers, enable_analytics, analytics_port
        )

        env = {**os.environ, "PYTHONUNBUFFERED": "1", "PYTHONIOENCODING": "utf-8"}
        kwargs: dict = {}
        if os.name != "nt":
            kwargs["start_new_session"] = True

        try:
            process = await asyncio.create_subprocess_exec(
                sys.executable, str(run_script),
                cwd=str(instance_dir),
                stdout=asyncio.subprocess.DEVNULL,
                stderr=asyncio.subprocess.DEVNULL,
                env=env,
                **kwargs,
            )
        except Exception:
            self._release_analytics_port(instance_id)
            await self._update_instance_status(
                instance_id, status=InstanceState.STOPPED, pid=None, db_session=db_session
            )
            raise

        self._processes[instance_id] = process
        self._watch_tasks[instance_id] = asyncio.create_task(
            self._watch_process(instance_id, process)
        )

        await self._update_instance_status(
            instance_id,
            status=InstanceState.RUNNING,
            pid=process.pid,
            analytics_port=analytics_port,
            db_session=db_session,
        )
        logger.info("Started subprocess instance %s PID=%d", instance_id, process.pid)
        return process.pid

    async def _watch_process(self, instance_id: str, process: asyncio.subprocess.Process) -> None:
        try:
            await process.wait()
            logger.info("Subprocess instance %s exited (code=%s)", instance_id, process.returncode)
        except Exception as e:
            logger.error("Error watching process %s: %s", instance_id, e)
        finally:
            self._processes.pop(instance_id, None)
            self._watch_tasks.pop(instance_id, None)
            self._release_analytics_port(instance_id)
            await self._update_instance_status(
                instance_id,
                status=InstanceState.STOPPED,
                pid=None,
                analytics_port=None,
                set_last_stopped_at=True,
            )

    async def stop(self, instance_id: str, db_session: AsyncSession | None = None) -> bool:
        """Gracefully stop a subprocess miner. Blocks until fully stopped."""
        GRACEFUL_TIMEOUT = 30
        FORCE_TIMEOUT = 10

        async def _fetch(db: AsyncSession) -> MinerInstance | None:
            result = await db.execute(
                select(MinerInstance).where(MinerInstance.id == instance_id)
            )
            return result.scalar_one_or_none()

        inst = await _fetch(db_session) if db_session else None
        if inst is None:
            async with async_session() as db:
                inst = await _fetch(db)

        if not inst or inst.status == InstanceState.STOPPED or not self._pid_exists(inst.pid):
            if inst and inst.status != InstanceState.STOPPED:
                inst.status = InstanceState.STOPPED
                inst.pid = None
                inst.last_stopped_at = datetime.now(timezone.utc)
                if db_session:
                    await db_session.commit()
                else:
                    async with async_session() as db:
                        await db.merge(inst)
                        await db.commit()
            return False

        pid = inst.pid
        logger.info("Stopping subprocess instance %s (PID=%d)", instance_id, pid)

        await self._update_instance_status(
            instance_id, status=InstanceState.STOPPING, pid=pid, db_session=db_session
        )

        try:
            self._signal_process(pid, signal.SIGTERM)
        except (ProcessLookupError, PermissionError, OSError) as e:
            logger.debug("SIGTERM for PID %d: %s", pid, e)

        local_proc = self._processes.get(instance_id)
        try:
            if local_proc and local_proc.returncode is None:
                await asyncio.wait_for(local_proc.wait(), timeout=GRACEFUL_TIMEOUT)
            else:
                exited = await self._wait_for_pid_exit(pid, GRACEFUL_TIMEOUT)
                if not exited:
                    raise asyncio.TimeoutError
        except asyncio.TimeoutError:
            logger.warning("Graceful stop timed out for %s, force-killing", instance_id)
            try:
                self._signal_process(pid, signal.SIGKILL)
            except (ProcessLookupError, PermissionError, OSError):
                pass
            if local_proc and local_proc.returncode is None:
                try:
                    await asyncio.wait_for(local_proc.wait(), timeout=FORCE_TIMEOUT)
                except asyncio.TimeoutError:
                    pass
            else:
                await self._wait_for_pid_exit(pid, FORCE_TIMEOUT)

        watch_task = self._watch_tasks.get(instance_id)
        if watch_task and not watch_task.done():
            try:
                await asyncio.wait_for(watch_task, timeout=5)
            except (asyncio.TimeoutError, asyncio.CancelledError):
                watch_task.cancel()

        self._processes.pop(instance_id, None)
        self._watch_tasks.pop(instance_id, None)
        self._release_analytics_port(instance_id)

        await self._update_instance_status(
            instance_id,
            status=InstanceState.STOPPED,
            pid=None,
            analytics_port=None,
            set_last_stopped_at=True,
            db_session=db_session,
        )
        return True

    # ------------------------------------------------------------------
    # Status reconciliation
    # ------------------------------------------------------------------

    async def reconcile_instance_status(
        self, instance_id: str, db_session: AsyncSession | None = None
    ) -> None:
        async def _reconcile(db: AsyncSession) -> None:
            result = await db.execute(
                select(MinerInstance).where(MinerInstance.id == instance_id)
            )
            inst = result.scalar_one_or_none()
            if not inst or inst.status != InstanceState.RUNNING:
                return
            if not self._pid_exists(inst.pid):
                inst.status = InstanceState.STOPPED
                inst.pid = None
                inst.last_stopped_at = datetime.now(timezone.utc)
                await db.commit()

        if db_session is not None:
            await _reconcile(db_session)
        else:
            async with async_session() as db:
                await _reconcile(db)

    async def reconcile_all_on_startup(self) -> None:
        async with async_session() as db:
            result = await db.execute(
                select(MinerInstance).where(
                    MinerInstance.miner_type == "subprocess",
                    MinerInstance.status != InstanceState.STOPPED,
                )
            )
            instances = result.scalars().all()
            changed = 0
            for inst in instances:
                if not self._pid_exists(inst.pid):
                    inst.status = InstanceState.STOPPED
                    inst.pid = None
                    inst.last_stopped_at = datetime.now(timezone.utc)
                    changed += 1
            if changed:
                await db.commit()
                logger.info("Reconciled %d stale subprocess instance(s) to STOPPED", changed)

    async def cleanup_orphan_processes(self) -> None:
        to_remove = [
            iid for iid, proc in self._processes.items() if proc.returncode is not None
        ]
        for iid in to_remove:
            self._processes.pop(iid, None)
            self._watch_tasks.pop(iid, None)
        await self.reconcile_all_on_startup()

    async def shutdown_all(self) -> None:
        async with async_session() as db:
            result = await db.execute(
                select(MinerInstance).where(
                    MinerInstance.miner_type == "subprocess",
                    MinerInstance.status != InstanceState.STOPPED,
                )
            )
            instances = result.scalars().all()
        for inst in instances:
            try:
                await self.stop(inst.id)
            except Exception as e:
                logger.error("Error stopping subprocess instance %s: %s", inst.id, e)


# Global singleton
process_manager = MinerProcessManager()
